version: "3.8"

services:
  jetson-benchmark:
    build:
      context: .
      dockerfile: Dockerfile.jetson

    image: jetson-benchmark
    container_name: jetson-benchmark
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=${DISPLAY}

    volumes:
      # Model export + results
      - /home/jetsonorin/exported_models:/workspace/exported_models
      - /home/jetsonorin/inference-result:/workspace/results

      # Your dataset
      - /home/jetsonorin/dataset/test/Benign:/workspace/test_folder

      # FIXED line (removed the accidental: jetson-benchmark)
      - /usr/src/tensorrt/bin/trtexec:/usr/local/bin/trtexec

      # This one was being IGNORED before — now it works
      - /home/jetsonorin/models:/workspace/models

      # Live editing scripts
      - ./benchmark_models.py:/workspace/benchmark_models.py
      - ./benchmark_models_plotly_jetson.py:/workspace/benchmark_models_plotly_jetson.py
      - ./benchmark_models_plotly.py:/workspace/benchmark_models_plotly.py
      - ./run_benchmark_example.py:/workspace/run_benchmark_example.py
      - ./export_models.py:/workspace/export_models.py
      - ./convert_to_trt.py:/workspace/convert_to_trt.py
      # GUI X11
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm

    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: bash

